name: CI Workflow

# Trigger the workflow on push to dev or main branches, or on pull request to dev or main branches
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

# Define the jobs for the workflow
jobs:
  # Build the project
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Log a message
        run: echo "Job triggered! ðŸš€"

      - name: Log multiple things
        run: |
          echo "This is my first GitHub Actions workflow"
          echo "Current date: $(date)"
          echo "Runner OS: ${{ runner.os }}"
